# Generated by Django 6.0.2 on 2026-02-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0006_alter_cartitem_product_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
