# Generated by Django 6.0.2 on 2026-02-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0007_alter_product_cover'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
