# Generated by Django 6.0.2 on 2026-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
